In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('./data/data_processed.csv', index_col=0)

In [3]:
df.iloc[2:, 1:39].head()

Water (g)  Energy (kal)  Protein (g)  lipid (g)  Carbohydrate (g)  \
2       5.31         628.0        14.95      60.75             16.70   
3      11.75         333.0        23.58       0.83             60.01   
4       6.50         567.0        25.80      49.24             16.13   
5      78.86          81.0         5.42       0.40             14.45   
6      12.89         360.0         6.61       0.58             79.34   

   Fiber (g)  Sugars (g)  Ash (g)  Ca (mg)  Fe (mg)  ...  Vd (IU)  Vk (µg)  \
2        9.7      4.3400      4.1    114.0     4.70  ...      0.0   14.200   
3       24.9      2.2300      0.9    143.0     8.20  ...      0.0   19.000   
4        8.5      4.7200      3.2     92.0     4.58  ...      0.0    0.000   
5        5.7      5.6700      1.1     25.0     1.47  ...      0.0   24.800   
6        0.4     20.3794      0.4      9.0     0.80  ...      0.0    2.625   

   saturated (g)  monounsaturated (g)  polyunsaturated (g)  trans (g)  \
2          4.464               45.652                7.920        0.0   
3          0.120                0.064                0.457        0.0   
4          6.279               24.426               15.558        0.0   
5          0.071                0.035                0.187        0.0   
6          0.158                0.181                0.155        0.0   

   Cholesterol (mg)  Caffeine (mg)  phenolics (mg)      pH  
2               0.0            0.0          274.00  6.8342  
3               0.0            0.0           27.40  5.7000  
4               0.0            0.0          356.70  7.5000  
5               0.0            0.0           85.50  6.5500  
6               0.0            0.0            0.28  6.3500  

[5 rows x 38 columns]

In [4]:
df.iloc[:, 1:39]

Water (g)  Energy (kal)  Protein (g)  lipid (g)  Carbohydrate (g)  \
0        90.20          32.0         5.00       0.70              2.90   
1        90.10          18.0         2.20       0.30              7.30   
2         5.31         628.0        14.95      60.75             16.70   
3        11.75         333.0        23.58       0.83             60.01   
4         6.50         567.0        25.80      49.24             16.13   
..         ...           ...          ...        ...               ...   
236      59.47         282.0        16.56      23.41              0.00   
237      87.59          44.0         1.06       0.32             10.55   
238      89.11          40.0         1.10       0.10              9.34   
239      88.90          37.0         2.10       0.40              8.00   
240      81.80          61.0         2.00       0.10             15.40   

     Fiber (g)  Sugars (g)  Ash (g)  Ca (mg)  Fe (mg)  ...  Vd (IU)  Vk (µg)  \
0          1.9      0.2000   1.2000    112.0     2.80  ...   1.9200   30.500   
1          4.3      3.5746   0.7000     62.0     0.80  ...   0.0192  159.208   
2          9.7      4.3400   4.1000    114.0     4.70  ...   0.0000   14.200   
3         24.9      2.2300   0.9000    143.0     8.20  ...   0.0000   19.000   
4          8.5      4.7200   3.2000     92.0     4.58  ...   0.0000    0.000   
..         ...         ...      ...      ...      ...  ...      ...      ...   
236        0.0      0.0000   1.0000     16.0     1.55  ...   2.0000    3.600   
237        1.7      7.8900   0.2836      6.0     0.28  ...   0.0000    2.200   
238        1.7      4.2400   0.5000     23.0     0.21  ...   0.0000    0.400   
239        1.8      4.1026   0.6000     24.0     0.80  ...   3.1785    9.254   
240        2.5      5.7088   0.7000     19.0     4.20  ...   4.0485   13.334   

     saturated (g)  monounsaturated (g)  polyunsaturated (g)  trans (g)  \
0          0.06900              0.05600              0.40900    0.00000   
1          0.30000              0.20000              0.50000    0.00000   
2          4.46400             45.65200              7.92000    0.00000   
3          0.12000              0.06400              0.45700    0.00000   
4          6.27900             24.42600             15.55800    0.00000   
..             ...                  ...                  ...        ...   
236       10.19000              9.60000              1.85000   12.74426   
237        0.02500              0.08800              0.11300    0.00000   
238        0.04200              0.01300              0.01700    0.00000   
239        0.03933              0.05991              0.11631    1.13010   
240        0.03557              0.01382              0.04731    1.42069   

     Cholesterol (mg)  Caffeine (mg)  phenolics (mg)      pH  
0                0.00            0.0          378.00  5.5651  
1                0.00            0.0           39.20  5.9220  
2                0.00            0.0          274.00  6.8342  
3                0.00            0.0           27.40  5.7000  
4                0.00            0.0          356.70  7.5000  
..                ...            ...             ...     ...  
236             73.00            0.0            0.00  6.0500  
237              0.00            0.0          533.00  4.0500  
238              0.00            0.0           84.50  5.4600  
239             27.17            0.0           56.28  5.3447  
240             29.41            0.0           25.66  5.5851  

[241 rows x 38 columns]

In [5]:
df["hot_cold_scale"][:]

0      0.500000
1      0.500000
2      0.500000
3      0.500000
4      0.500000
         ...   
236    0.666667
237    0.666667
238    0.666667
239    0.666667
240    0.666667
Name: hot_cold_scale, Length: 241, dtype: float64

In [6]:
# TO DO label encoder, temp solution
df['hot_cold_scale'] = df['hot_cold_scale'] * 10
df['hot_cold_scale'] = df['hot_cold_scale'].astype(int)

### Logistic Regression

In [7]:
def logistic_regression(df, y_col_name):
    """
    Apply sample logistic regression model to dataframe

    df : (dataframe)
    x : (compounds column as int)
    y : (classification column as int)
    """
    # values of each column
    x = df.iloc[:, 1:39] # df.iloc[2:, 1:39]??
    y = df[y_col_name][:]

    # split data into training and test set
    # 75 training, 25 testing
    xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

    # standardize and scale data
    scaler = StandardScaler()
    xtrain = scaler.fit_transform(xtrain)
    xtest = scaler.transform(xtest)

    # modeling + analysis
    model = LogisticRegression(random_state=0)
    model.fit(xtrain, ytrain.ravel())
    y_pred = model.predict(xtest)

    # confusion matrix of test size
    conf_m = confusion_matrix(ytest, y_pred)
    print("Confusion Matrix : ", conf_m)

    # accuracy score of test size
    print ("Accuracy : ", accuracy_score(ytest, y_pred))

In [8]:
logistic_regression(df, "hot_cold_scale")

Confusion Matrix :  [[0 0 0 1 0 1 1 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 3 4 0 0]
 [0 0 1 6 0 3 3 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 3 0 9 1 1 0]
 [0 0 1 0 0 2 2 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0 0]]
Accuracy :  0.3469387755102041


/Users/aaronxie/.local/share/virtualenvs/analysis-gniU7RWb/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### KNN

In [9]:
def knn(df, y_col_name):
    x = df.iloc[:, 1:39]
    y = df[y_col_name][:]
    
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
    knn = KNeighborsClassifier(n_neighbors = 5)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    
    print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [10]:
knn(df, "hot_cold_scale")

Accuracy :  0.22448979591836735


/Users/aaronxie/.local/share/virtualenvs/analysis-gniU7RWb/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
